# distributed training
nodes: 1
gpus: 1 # I recommend always assigning 1 GPU to 1 node
nr: 0 # machine nr. in node (0 -- nodes - 1)
dataparallel: 0 # Use DataParallel instead of DistributedDataParallel
workers: 12

# Data option
modality: [mri, tau]
ad: False
mci: True
trans_tau: True
stable: False
dir_label: '../getlabels'
num_label: 2
resize: False
resize64: False
dir_data: '../caps/subjects'
clinica: False
transform: False
save_samples: False
t1_linear: True
finetune: False
clinica: True
roi: False
# train options
seed: 43 # sacred handles automatic seeding when passed in the config
batch_size: 64
image_size: (182,218,182)
flatten_shape: 128*6*7*6
start_epoch: 0
epochs: 1000
scheduler: False
dropout: 0.5
patience: 1000
weight_decay: 0.0
lr: 1.0e-4
optimizer: sgd
temperature: 0.07
# model options
model: Conv5FC3
projection_dim: 64
# reload options
model_path: "transfer/mri/simpleconv/t1linear"


