# distributed training
nodes: 1
gpus: 1 # I recommend always assigning 1 GPU to 1 node
nr: 0 # machine nr. in node (0 -- nodes - 1)
dataparallel: 0 # Use DataParallel instead of DistributedDataParallel
workers: 12

# Data option
modality: mri
ad: True
mci: True
trans_tau: False
stable: False
dir_label: '../getlabels'
num_label: 3
free: '_coreg' # '_coreg' if Data_free
resize: False
dir_data: '../caps_new/subjects'
transform: False
flip: False
local_shuffle_pixel: False
non_inear_ransformation: False
in_painting: False
out_painting: False
clinica: True
save_samples: False
t1_linear: True

# train options
seed: 43 # sacred handles automatic seeding when passed in the config
batch_size: 12
image_size: (128,128,128)
start_epoch: 0
epochs: 50
finetune: False
scheduler: False
lr: 1.0e-4
patience: 0

# model options
model: autoencoder

# loss options
weight_decay: 0.0
# reload options
model_path: "autoencoder_t1_linear"
